version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: mentech
      POSTGRES_PASSWORD: mentech
      POSTGRES_DB: mentech
    restart: always
    networks:
      - mentech-network
networks:
  mentech-network:
